/*
Copyright 2018 The Voyager Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by lister-gen

package v1

// PMDAsNumberListerExpansion allows custom methods to be added to
// PMDAsNumberLister.
type PMDAsNumberListerExpansion interface{}

// PMDAsNumberNamespaceListerExpansion allows custom methods to be added to
// PMDAsNumberNamespaceLister.
type PMDAsNumberNamespaceListerExpansion interface{}

// PMDRouteListerExpansion allows custom methods to be added to
// PMDRouteLister.
type PMDRouteListerExpansion interface{}

// PMDRouteNamespaceListerExpansion allows custom methods to be added to
// PMDRouteNamespaceLister.
type PMDRouteNamespaceListerExpansion interface{}
