/*
Copyright 2018 The Voyager Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by informer-gen

package v1

import (
	pmd_v1 "snaproute-operator/pkg/apis/pmd/v1"
	versioned "snaproute-operator/pkg/client/clientset/versioned"
	internalinterfaces "snaproute-operator/pkg/client/informers/externalversions/internalinterfaces"
	v1 "snaproute-operator/pkg/client/listers/pmd/v1"
	time "time"

	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// PMDRouteInformer provides access to a shared informer and lister for
// PMDRoutes.
type PMDRouteInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.PMDRouteLister
}

type pMDRouteInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewPMDRouteInformer constructs a new informer for PMDRoute type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewPMDRouteInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredPMDRouteInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredPMDRouteInformer constructs a new informer for PMDRoute type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredPMDRouteInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options meta_v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.PmdV1().PMDRoutes(namespace).List(options)
			},
			WatchFunc: func(options meta_v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.PmdV1().PMDRoutes(namespace).Watch(options)
			},
		},
		&pmd_v1.PMDRoute{},
		resyncPeriod,
		indexers,
	)
}

func (f *pMDRouteInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredPMDRouteInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *pMDRouteInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&pmd_v1.PMDRoute{}, f.defaultInformer)
}

func (f *pMDRouteInformer) Lister() v1.PMDRouteLister {
	return v1.NewPMDRouteLister(f.Informer().GetIndexer())
}
