/*
Copyright 2018 The Voyager Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by informer-gen

package v1

import (
	bgp_v1 "snaproute-operator/pkg/apis/bgp/v1"
	versioned "snaproute-operator/pkg/client/clientset/versioned"
	internalinterfaces "snaproute-operator/pkg/client/informers/externalversions/internalinterfaces"
	v1 "snaproute-operator/pkg/client/listers/bgp/v1"
	time "time"

	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// BGPAsNumberInformer provides access to a shared informer and lister for
// BGPAsNumbers.
type BGPAsNumberInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.BGPAsNumberLister
}

type bGPAsNumberInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewBGPAsNumberInformer constructs a new informer for BGPAsNumber type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewBGPAsNumberInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredBGPAsNumberInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredBGPAsNumberInformer constructs a new informer for BGPAsNumber type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredBGPAsNumberInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options meta_v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.BgpV1().BGPAsNumbers(namespace).List(options)
			},
			WatchFunc: func(options meta_v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.BgpV1().BGPAsNumbers(namespace).Watch(options)
			},
		},
		&bgp_v1.BGPAsNumber{},
		resyncPeriod,
		indexers,
	)
}

func (f *bGPAsNumberInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredBGPAsNumberInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *bGPAsNumberInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&bgp_v1.BGPAsNumber{}, f.defaultInformer)
}

func (f *bGPAsNumberInformer) Lister() v1.BGPAsNumberLister {
	return v1.NewBGPAsNumberLister(f.Informer().GetIndexer())
}
